language: node_js

node_js: 
  - "8"

install: npm install

before_script:
- npm run start
after_success:
  npm run coverage

#before_install:
#  - npm i -g mocha babel-preset-env chai chai-http babel-cli nyc coveralls
#  - npm start

